title: "[General] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: textarea
    id: improvements
    attributes:
      label: Description
      description:
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
