title: "[Dataset Name] "
labels: ["data"]
body:
  - type: Dataset Description
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: textarea
    id: dataset-description
    attributes:
      label: Describe the new dataset
      value: |
 
      render: bash
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
  - type: markdown
    attributes:
      value: |
        ## Data specifications
  - type: input
    id: has-id
    attributes:
      label: Timeframe
      description: A description about suggestions to help you
    validations:
      required: true
  - type: Ecosystem Component
    id: download
    attributes:
      label: Which area of this project could be most improved?
      options:
        - Documentation
        - Pull request review time
        - Bug fix time
        - Release cadence
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
