title: "[Dataset Name] "
labels: ["data"]
body:
  - type: markdown
    attributes:
      value: |
        ## Dataset
  - type: input
    id: contact
    attributes:
      label: Contact
      description: "[Name] [Email]"
    validations:
      required: true
  - type: textarea
    id: improvements
    attributes:
      label: Description
      description:
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

