title: "[Dataset Name] "
labels: ["data"]
body:
  - type: markdown
    attributes:
      value: |
        ## Dataset Information
  - type: input
    id: contact
    attributes:
      label: Contact
      description: "[Name] [Email]"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
       Description...
       Caveats...
       ...
      description:
      render: bash
    validations:
      required: true
  - type: input
    id: timeframe
    attributes:
      label: Timeframe
      description: What is the timeframe of the dataset?
    validations:
      required: true
  - type: dropdown
    id: qc
    attributes:
      label: Has this data been quality controlled?
      options:
      - "Yes"
      - "No"
    validations:
      required: true
